version: '3'

services:
  db:

  backend:
    build: 
      context: ./backend
  
  frontend:
    build: 
      context: ./frontend


  nginx:
    build: ./nginx
    port: 
      - 80:8080 


  volumes: 
    