version: '3'

services:
  mongodb: 
    image: mongo:latest
    container_name: mongo 
    restart: unless-stopped
    command: mongod --auth 
    volumes:
      - mongo_db: /data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: 123123
      MONGO_INITDB_DATABASE: webapp
      MONGODB_DATA_DIR: /data/db

    prots: 
      - 27017:27017

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app 
    ports: 
      - 5000:5000
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: "apiuser"
      MONGODB_PASSWORD: "apipassword"
    volumes:
      - appdata:/var/www/
    depends_on:
      - mongo_db
    networks:
      - frontend
      - backend
  
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    tty: true 
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend 



  nginx:
    image: nginx:latest
    container_name: nginx_service

    ports:
      - "8080:8080"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  frontend:
    driver: bridge
  backend: 
    driver: bridge

volumes:
  mongo_db:
    driver: local 
  appdata:
    driver: local