version: '3'

services:
  mongodb: 
    image: mongo:latest
    container_name: mongo 
    restart: unless-stopped
    command: mongod --auth 
    volumes:
      - mongodb:/data/db 

    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: chamomile123
      MONGO_INITDB_DATABASE: Book_data_DB
      MONGODB_DATA_DIR: mongodb:/data/db

    ports: 
      - 27017:27017


  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5001 app:app 
    ports: 
      - 5001:5001
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: root 
      MONGODB_PASSWORD: chamomile123
    volumes:
      - ./backend/:/app
    depends_on:
      - mongodb


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile 
    ports: 
      - 3000:3000
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_service

  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - backend
  #     - frontend
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf


volumes:
  mongodb:


  # mongodb 접속에 대해서 물어보기